# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/lasernet/lasernet.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/lasernet/lasernet.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/lasernet/lasernet.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet {{c:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/lasernet/lasernet.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}
set_property used_in_implementation false [get_files {{c:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/lasernet/lasernet.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp}}]
read_mem {{C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/cstring/font_rom.mif}}
read_verilog -library xil_defaultlib {
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/cstring/font_rom.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/cstring/cstringdisp.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/synchronize.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/mainfsm.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/display_8hex.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/debounce.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/xvga.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/blob.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/interface.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/ps2_kbd.v}
  {C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/nexys-wrapper.v}
}
read_edif {{C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/cstring/font_rom.edn}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/Nexys4DDR_Master_lab4.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Allan/Documents/MIT/FALL 2016/6.111/final project/Nexys4DDR_Master_lab4.xdc}}]


synth_design -top labkit -part xc7a100tcsg324-3


write_checkpoint -force -noxdef labkit.dcp

catch { report_utilization -file labkit_utilization_synth.rpt -pb labkit_utilization_synth.pb }
